name: build-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvmrc
        uses: pCYSl5EDgo/cat@master
        with:
          path: ./.nvmrc
          trim: true

      - name: Set Env Variables
        id: set-env
        uses: allenevans/set-env@v1.1.1
        with:
          overwrite: false
          DOCKER_REGISTRY: "docker.pkg.github.com"
          DOCKER_REPO_OWNER: "stefanwalther"
          DOCKER_REPO_NAME: "besser-app-api"
          DOCKER_IMAGE_NAME: "besser-app-api"
          DOCKER_IMAGE_TAG: "latest"
          NODE_VER: "${{ steps.nvmrc.outputs.text }}"

      - name: build
        id: build
        run: |
          make build

      - name: build-test
        id: build-test
        run: |
          make build-test

      - name: linter
        id: run-linter
        run: |
          make run-linter

      - name: tests
        run: make run-tests

      - name: publish to registry (only master)
        if: github.ref == 'refs/heads/master'
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} --username ${{ env.DOCKER_REPO_OWNER }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO_OWNER}}/${{ env.DOCKER_REPO_NAME }}/${{ env.DOCKER_IMAGE_NAME}}:${{ env.DOCKER_IMAGE_TAG }}

